# Generated by Django 5.2.1 on 2025-06-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['x'],
            },
        ),
        migrations.CreateModel(
            name='InterpolationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Set', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.ManyToManyField(related_name='sets', to='interpolation_app.interpolationpoint')),
            ],
        ),
        migrations.CreateModel(
            name='LagrangeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polynomial_coefficients', models.TextField()),
                ('evaluation_points', models.TextField()),
                ('evaluation_results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interpolation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interpolation_app.interpolationset')),
            ],
        ),
    ]
